CREATE TABLE USERS(U_ID INT PRIMARY KEY,NAME VARCHAR(20),
EMAIL VARCHAR(30));
INSERT INTO USERS VALUE(1,'ROHIT','sahnir260@gmail.com');

DROP TABLE ALBUMS;

CREATE TABLE ALBUMS(ALBUMID INT PRIMARY KEY,ALBUM_NAME TEXT);
INSERT INTO ALBUMS VALUES(1,'BEAUTY BEHIND THE MADNESS'),(2,'EVOLVE'),
(3,'ATTENTION'),
(4,'SUMMER BROTHERS'),
(5,'HOLLYWOOD BLEEDING');

CREATE TABLE SONGS(SONGID INT PRIMARY KEY,TITLE_OF_SONG VARCHAR(40),
ARTIST VARCHAR(30),GENRE VARCHAR(30), DURATION TIME,ALBUMID INT,
 FOREIGN KEY (ALBUMID) REFERENCES ALBUMS(ALBUMID));
 
 INSERT INTO SONGS VALUES(1,'The Hills','WEEKND','ROCK','3.40',1),
 (2,'Often','WEEKND','POP','03:50:00',1),
 (3,'Whatever It Take','Imagine Dragons','Motivation','4.34',2),
 (4,'The Way I Am','Charlie Puth','Pop','3.45',3),
 (5,'Easier','5 Seconds Of Summer','Electronic','3.30',4),
 (6,'Hollywoods Bleeding','Post Malone','JAZZ','4.20',5);
 
 select s.songid, s.title_of_song, s.duration, a.album_name, s.genre, s.artist from songs s inner join albums a
 on s.albumid = a.albumid where title_of_song like 'T%';
 
 
 DROP TABLE SONGS;
 
 CREATE TABLE PODCAST(PID INT PRIMARY KEY,PODACAST_NAME TEXT, CELEBRITY_NAME VARCHAR(30),DESCRIPTIONS TEXT,
 DURATION TIME, PUBLISHED_DATE DATETIME);
INSERT INTO PODCAST VALUES(1,'HEAD OR HEART','SADHGURU',
'HOW TO MAKE DECISIONS WHEN OUR HEART SEEMS TO SAY ONE THING AND THE HEAD SEEMS TO SAY ANOTHER THING.',
'00:08:00','2022-02-15'),(2,'INDIAN NEW','FIROZ',
'GIVES YOU THE INFORMATION OF BUDGETS',
'00:10:00','2022-01-12'),(3,'DESI CRIME','ARYAN MISRA',
'THE DESI CRIME PODCAST BRING YOU DESI CRIMES.',
'00:15:00','2022-01-10');
DROP TABLE PODCAST;

CREATE TABLE PLAYLIST(PLAYLIST_ID INT PRIMARY KEY auto_increment,PLAYLIST_NAME VARCHAR(30),
 TRACK_TYPE VARCHAR(30),TRACK_NAME VARCHAR(30), SID INT,PID INT,FOREIGN KEY (SID) REFERENCES SONGS(SONGID),
 FOREIGN KEY (PID) REFERENCES PODCAST(PID))auto_increment=1;
 
 drop table playlist;
 SELECT * FROM USERS;
 SELECT * FROM ALBUMS;
 SELECT * FROM SONGS;
 SELECT * FROM PODCAST;
 SELECT * FROM PLAYLIST;
 
 SELECT *FROM SONGS WHERE TITLE_OF_SONG LIKE 'T%';
 